# Generated by Django 3.1.3 on 2020-11-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agenda', models.DateTimeField()),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clinicaprofile')),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidade')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicoprofile')),
            ],
        ),
    ]
